- ipfs/docker-compose.yml
> Adding sample compose file for running IPFS with docker-compose

- remarkjs/Dockerfile
- remarkjs/README.md
- remarkjs/docker-entrypoint.sh
- remarkjs/index.html.tmpl
- remarkjs/styles.css
Allows the providing of my own `styles.css` to customize the look and feel of the presentation.
> Allow style overriding

- caddyproxy/Caddyfile.tmpl
- caddyproxy/Dockerfile
- caddyproxy/README.md
- caddyproxy/docker-entrypoint.sh
> Adding hairyhenderson/caddyproxy image

- ssh/Dockerfile
> Adding hairyhenderson/ssh

- sed/Dockerfile
- sed/README.md
> Adding a GNU sed image

- figlet/Dockerfile
Use `--no-cache` to avoid having to manually clean the cache!
> Make things more efficient

- nodejs-ci-build/Dockerfile
An image for building some of my node.js repos with CircleCI 2.0...
> Add nodejs-ci-build Dockerfile

- gomplate-ci-build/Dockerfile
Necessary to make hairyhenderson/gomplate#178 pass integration testing.
> Adding consul into the build image, for testing

- swarm-tools/Dockerfile
> Adding swarm tools image

- trx/Dockerfile
> Adding hairyhenderson/trx image

- socat/Dockerfile
- socat/README.md
> Adding a socat image

- .circleci/config.yml
- raspbian/Dockerfile
- raspbian/Makefile
Makes life a bit easier for hacking on Raspberry Pis...
> Adding raspbian image

- gomplate-ci-build/Dockerfile
Some updates, and some removals
> Updating gomplate-ci-build Dockerfile

- upx/Dockerfile
> Downgrade upx to 3.94

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- bashbrew/Dockerfile
- dockerfiles-builder/Dockerfile
- library/upx
> Try building some images with bashbrew

- .github/workflows/build.yml.tmpl
Fixes build failures such as https://github.com/hairyhenderson/dockerfiles/pull/96/checks?check_run_id=398544944
> only login on master builds

- gomplate-ci-build/Dockerfile
> Bump Go to 1.14.2

- gomplate-ci-build/Dockerfile
> Add buildx plugin to gomplate-ci-build image

- gomplate-ci-build/Dockerfile
> Add reg to gomplate-ci-build image

- bashbrew/Dockerfile
- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
- man/Dockerfile
> Upgrades (and fixes)

- caddyproxy/Dockerfile
- man/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
- ssh/Dockerfile
> Bump to alpine:3.12

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
> Switch to GHCR

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- .github/workflows/gen_workflows.yml
Just avoids an annoying warning 😉
> ci: Pin to ubuntu-20.04

- bashbrew/Dockerfile
- dockerfiles-builder/Dockerfile
- figlet/Dockerfile
- gomplate-ci-build/Dockerfile
- iptables/Dockerfile
- pi-blaster/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
- ssh/Dockerfile
- swarm-tools/Dockerfile
> bump to alpine:3.13.2

- dockerfiles-builder/Dockerfile
- github_changelog_generator/Dockerfile
- gomplate-ci-build/Dockerfile
- jwt/Dockerfile
- man/Dockerfile
- raspbian/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
- ssh/Dockerfile
- trx/Dockerfile
> Fix build & update

- bashbrew/Dockerfile
- dockerfiles-builder/Dockerfile
- figlet/Dockerfile
- gomplate-ci-build/Dockerfile
- jwt/Dockerfile
- man/Dockerfile
- pi-blaster/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
- ssh/Dockerfile
- swarm-tools/Dockerfile
> version bumps

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
> Add trivy scan job

- library/upx
- upx/Dockerfile
> Fix upx build

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
> some build fixes

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
> also run on pushes to master

- .github/workflows/build.yml
- nodejs-ci-build/Dockerfile
I don't use this anymore, and, frankly, neither should anyone else. The maintenance effort isn't worth it.
I won't delete the pushed images (yet), but it'll stop getting updates.
> Stop building nodejs-ci-build

- .trivyignore
- gomplate-ci-build/Dockerfile
- raspbian/Dockerfile
- trx/Dockerfile
> Avoid trivy vulns in gomplate-ci-build

- remarkjs/Dockerfile
> remarkjs: Avoid CVE-2021-3517/CVE-2021-3518/CVE-2021-3537

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- .gitignore
- .trivyignore
- Makefile
- bashbrew/Dockerfile
- dockerfiles-builder/Dockerfile
- figlet/Dockerfile
- gomplate-ci-build/Dockerfile
- library/upx
- man/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
- ssh/Dockerfile
- upx/Dockerfile
> some fixes

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- Makefile
- dockerfiles-builder/.docker-platforms
- gomplate-ci-build/.docker-platforms
> Attempt to build with buildx

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- .trivyignore
> Ignore CVE-2020-9283 and CVE-2020-29652

- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
> A bunch of bumps

- .github/dependabot.yml
- .github/dependabot.yml.tmpl
- .github/workflows/build.yml
- golang-air/Dockerfile
Just a simple utility image for local dev setups - I may build on this later...
> Add golang-air image

- bashbrew/Dockerfile
- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
- iptables/Dockerfile
- man/Dockerfile
- pi-blaster/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
- swarm-tools/Dockerfile
- upx/Dockerfile
> Upgrading a bunch of Dockerfiles to use alpine:3.15

- .trivyignore
- gomplate-ci-build/Dockerfile
> Update buildx plugin dep

- golang-air/Dockerfile
- gomplate-ci-build/Dockerfile
> Upgrade linux-libc-dev to patch for some CVEs

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- golang-air/Dockerfile
- gomplate-ci-build/.tag-args
- gomplate-ci-build/Dockerfile
- jwt/Dockerfile
- swarm-tools/Dockerfile
> Bump to Go 1.18

- gomplate-ci-build/Dockerfile
> Bump golangci-lint to 1.45

- jwt/Dockerfile
> move from unmaintained dgrijalva/jwt-go to golang-jwt/jwt

- .trivyignore
- gomplate-ci-build/Dockerfile
- trx/Dockerfile
> Update to patch/workaround some CVEs

- Makefile
- gomplate-ci-build/Dockerfile
- trx/Dockerfile
> Update for CVE-2022-1271

- remarkjs/Dockerfile
> Workaround CVE-2022-27404

- .trivyignore
- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
- remarkjs/Dockerfile
> bump gomplate v3.11.0

- .trivyignore
> Removing most CVE ignores

- .github/dependabot.yml
- .github/workflows/build.yml
- ci-builder/.docker-platforms
- ci-builder/.tag-args
- ci-builder/Dockerfile
to replace gomplate-ci-builder
> New alpine-based ci-builder image

- .gitignore
- Makefile
- ci-builder/Dockerfile
> Add missing packages to ci-builder

- .trivyignore
- Makefile
- ci-builder/Dockerfile
- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
> Track minors

- Makefile
- ci-builder/Dockerfile
- golang-air/Dockerfile
- gomplate-ci-build/Dockerfile
- jwt/Dockerfile
> Bump to Go 1.19

- ci-builder/Dockerfile
- gomplate-ci-build/Dockerfile
> Update golangci-lint to 1.48

- .trivyignore
- ci-builder/Dockerfile
- gomplate-ci-build/Dockerfile
> ignore a few vulns

- bashbrew/Dockerfile
- ci-builder/Dockerfile
- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
- man/Dockerfile
- pi-blaster/Dockerfile
- sed/Dockerfile
- socat/Dockerfile
> Bump to alpine:3.17

- .github/workflows/build.yml
- .github/workflows/build.yml.tmpl
- .trivyignore
- ci-builder/Dockerfile
- dockerfiles-builder/Dockerfile
- gomplate-ci-build/Dockerfile
Fixes e.g. https://github.com/caddyserver/caddy-docker/actions/runs/4111806904/jobs/7112679649
> Add buildx to dockerfiles-builder

- .trivyignore
- ci-builder/Dockerfile
- gomplate-ci-build/Dockerfile
Avoid irrelevant vulns, update golangci-lint
> some updates
